# -*- coding: utf-8 -*-
"""Seaborn: Scatterplot & Catplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nB9OM66L2n2kCt8bbUtNprE5wUkEazzs

**Persiapan Data**
"""

from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

#menghilangkan tanda "warning" pada output agar terlihat lebih rapi
from warnings import filterwarnings
filterwarnings('ignore')

#dataset berupa data "diamonds" yang telah disediakan oleh Seaborn
df = sns.load_dataset('diamonds')
df.head()

"""**Scatterplot**"""

#membuat custom figure
sns.set({'figure.figsize':(12,14)})
palette = "ch:r=-.2,d=.3_r"

#memuat data untuk scatterplot
sns.scatterplot(data=df, 
                x='carat', 
                y='price', 
                hue='clarity', 
                size='depth', 
                palette=palette, 
                sizes=(0,10), 
                linewidth=0)

"""Scatterplot diatas menggambarkan data dari dataset "diamonds" yang menunjukkan sebaran dari variabel *carat* dengan *price* serta menghubungkannya dengan variabel *clarity* dan *depth* melalui ukuran dan warna dari scatterplot yang dibentuk. 
Salah satu informasi yang didapat dari visualisasi diatas adalah bahwa terdapat banyak diamonds pada rentang harga antara 0 - 10000 yang ditunjukkan dengan sebaran data yang rapat, sedangkan harga >10000 memiliki sebaran data yang renggang.

**Categorical-Plot**
"""

with sns.axes_style(style='ticks'):
  g = sns.catplot('clarity', 'price', data=df, kind='box', showfliers=False, col='cut')
  g.set_axis_labels('Clarity', 'Price')